"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _connections from './connections.bones.json'
import _system_stats from './system-stats.bones.json'
import _network_settings from './network-settings.bones.json'
import _session_settings from './session-settings.bones.json'
import _portal_settings from './portal-settings.bones.json'
import _coin_settings from './coin-settings.bones.json'
import _loyalty_settings from './loyalty-settings.bones.json'
import _vouchers from './vouchers.bones.json'
import _devices from './devices.bones.json'
import _system_settings from './system-settings.bones.json'
import _logs from './logs.bones.json'
import _dashboard from './dashboard.bones.json'

registerBones({
  "connections": _connections,
  "system-stats": _system_stats,
  "network-settings": _network_settings,
  "session-settings": _session_settings,
  "portal-settings": _portal_settings,
  "coin-settings": _coin_settings,
  "loyalty-settings": _loyalty_settings,
  "vouchers": _vouchers,
  "devices": _devices,
  "system-settings": _system_settings,
  "logs": _logs,
  "dashboard": _dashboard,
})
